---

- hosts: web:db
  become: yes 


  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present

  - name: Bring the Apache Service
    service: name=apache2 state=started

  - name: Deploy Custom Web Page
    copy: src=templates/index.html dest=/var/www/html/index.html

  - name: Download Mario Image from Web.
    get_url: url=http://www.mariomayhem.com/downloads/wallpapers/7/nsmb_wp7_1280.jpg dest=/var/www/html/mario.jpg mode=0755

  - name: Deploy Info Template.
    template: src=templates/info.j2 dest=/var/www/html/info.html

  - name: Install JDK Packages
    apt: name=openjdk-8-jdk state=present

  - name: Copy Atmosphere application jar
    copy: src=./spring-boot-sample-atmosphere-1.4.0.BUILD-SNAPSHOT.jar dest=/usr

  - name: Install Atmosphere application
    shell: "/usr/bin/java -jar /usr/spring-boot-sample-atmosphere-1.4.0.BUILD-SNAPSHOT.jar"
